stages:
  - build
  - prepare
  - deploy

services:
  - docker:dind

variables:
  IMAGE_STAGED: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  IMAGE_RELEASE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

before_script:
  - export DOCKER_BUILDKIT=1
  - export COMPOSE_DOCKER_CLI_BUILD=1
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: docker
  script:
    - echo ${IMAGE_STAGED}
    - docker build --target prod -t ${IMAGE_STAGED}-app app
    - docker build --target prod -t ${IMAGE_STAGED}-ingress docker/nginx
    - docker push ${IMAGE_STAGED}-app
    - docker push ${IMAGE_STAGED}-ingress

rename:
  stage: prepare
  only:
    - tags
  dependencies:
    - build
  image: docker
  script:
    - docker image tag ${IMAGE_STAGED}-app ${IMAGE_RELEASE}-app
    - docker image tag ${IMAGE_STAGED}-ingress ${IMAGE_RELEASE}-ingress
    - docker push ${IMAGE_RELEASE}-app
    - docker push ${IMAGE_RELEASE}-ingress

dev:
  stage: deploy
  tags:
    - deploy
  when: manual
  except:
    - tags
  dependencies:
    - build
  variables:
    COMPOSE_PROJECT_NAME: my-blog-dev
  script:
    - docker-compose -f docker-compose.prod.yml up -d --remove-orphans
  environment:
    name: dev
    url: https://blog-dev.marcus-rise.dev/
