version: "3.4"

services:
  app:
    image: ${CONTAINER_REGISTRY}-app
    volumes:
      - static:/app/dist/client/.next
    environment:
      API_END_POINT: ${API_END_POINT}

  ingress:
    image: ${CONTAINER_REGISTRY}-ingress
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - static:/etc/nginx/html/_next:ro

volumes:
  static:
