version: "3.4"

services:
  app:
    image: ${CONTAINER_REGISTRY}-app
    volumes:
      - static:/app/dist/client/.next
    environment:
      API_END_POINT: ${API_END_POINT}
      ALLOWED_CONTENT_ORIGIN: ${ALLOWED_CONTENT_ORIGIN}

  web:
    image: ${CONTAINER_REGISTRY}-web
    links:
      - app
    volumes:
      - static:/etc/nginx/html/_next:ro

  ingress:
    image: ${CONTAINER_REGISTRY}-ingress
    links:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/ingress/ssl:/var/lib/https-portal
    environment:
      DOMAINS: "${DOMAIN} -> http://web"
      STAGE: "production"

volumes:
  static:
