version: "3.4"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  admin:
    build:
      context: admin
      target: "dev"
    volumes:
      - ./admin:/app
    links:
      - db
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  app:
    build:
      context: app
      target: "dev"
    links:
      - admin
    volumes:
      - ./app:/app:rw
    ports:
      - '3000:3000'
      - '9229:9229'

  ingress:
    build:
      context: docker/ingress
      target: "dev"
    links:
      - app
      - admin
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl:/var/lib/https-portal
      - ./docker/ingress/default.ssl.conf.erb:/var/lib/nginx-conf/default.ssl.conf.erb:ro
      - ./docker/nginx/502.html:/etc/nginx/html/502.html
      - ./app/src/client/.next:/etc/nginx/html/_next
    environment:
      STAGE: local
      DOMAINS: '${DOMAIN}'
      ACCESS_LOG: 'true'

volumes:
  ssl:
