version: "3.4"

services:
  admin:
    build:
      context: admin
      target: "prod"
    volumes:
      - ./admin/.tmp:/app/.tmp
    ports:
     - '1337:1337'

  app:
    build:
      context: app
      target: "prod"
    ports:
    - '3000:3000'

