version: "3.4"

services:
  app:
    build:
      context: app
      target: "prod"
    environment:
      API_END_POINT: ${API_END_POINT}
    volumes:
      - static:/app/dist/client/.next

  ingress:
    build:
      context: docker/nginx
      target: "prod"
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - static:/etc/nginx/html/_next:ro

volumes:
  static:
