version: "3.4"

services:
  admin:
    build:
      context: admin
      target: "prod"
    volumes:
      - ./admin/.tmp:/app/.tmp
    environment:
      DOMAIN: admin.${DOMAIN}

  app:
    build:
      context: app
      target: "prod"
    volumes:
      - static:/app/dist/client/.next

  web:
    build:
      context: docker/nginx
      target: "prod"
    links:
      - app
      - admin
    volumes:
      - static:/etc/nginx/html/_next:ro

  ingress:
    build:
      context: docker/ingress
    links:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl:/var/lib/https-portal
    environment:
      STAGE: local
      DOMAINS: '${DOMAIN} -> http://web, admin.${DOMAIN} -> http://admin:1337'
      ACCESS_LOG: 'true'

volumes:
  static:
  ssl:
