version: "3.4"

services:
  app:
    build:
      context: app
      target: "dev"
    volumes:
      - ./app:/app:rw
    ports:
      - '3000:3000'
      - '9229:9229'
    env_file:
      - .env

  ingress:
    build:
      context: docker/nginx
      target: "dev"
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/502.html:/etc/nginx/html/502.html:ro
      - ./app/src/client/.next:/etc/nginx/html/_next:ro
      - ./app/src/client/public:/etc/nginx/html/static:ro
