version: "3.4"

services:
  admin:
    image: strapi/strapi
    volumes:
      - ./admin:/srv/app
    ports:
     - '1337:1337'

  app:
    build:
      context: app
      target: "dev"
    volumes:
    - ./app:/app
    ports:
    - '3000:3000'

