version: "3.4"

services:
  app:
    build:
      context: app
      target: "prod"
    volumes:
      - static:/app/dist/client/.next
    environment:
      API_END_POINT: ${API_END_POINT}
      ALLOWED_CONTENT_ORIGIN: ${ALLOWED_CONTENT_ORIGIN}

  web:
    build:
      context: docker/nginx
      target: "prod"
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - static:/etc/nginx/html/_next:ro

  ingress:
    build:
      context: docker/ingress
    links:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/ingress/ssl:/var/lib/https-portal
    environment:
      DOMAINS: "${DOMAIN} -> http://web"
      STAGE: "local"
      LISTEN_IPV6: "true"

volumes:
  static:
