version: "3.4"

services:
  admin:
    build:
      context: admin
      target: "prod"
    volumes:
      - ./admin/.tmp:/app/.tmp
    ports:
      - '1337:1337'

  app:
    build:
      context: app
      target: "prod"
    volumes:
      - static:/app/dist/client/.next

  web:
    build:
      context: docker/nginx
      target: "prod"
    links:
      - app
      - admin
    ports:
      - 8080:80
    volumes:
      - static:/etc/nginx/html/_next:ro

volumes:
  static:

