version: "3.4"

services:
  admin:
    build:
      context: admin
      target: "dev"
    volumes:
      - ./admin:/srv/app
    ports:
      - '1337:1337'

  app:
    build:
      context: app
      target: "dev"
    volumes:
      - ./app:/app:rw
    ports:
      - '3000:3000'
      - '9229:9229'

  web:
    build:
      context: docker/nginx
      target: "dev"
    links:
      - app
      - admin
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/502.html:/etc/nginx/html/502.html
      - ./app/src/client/.next:/etc/nginx/html/_next
