version: "3.4"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  admin:
    build:
      context: admin
      target: "prod"
      args:
        DOMAIN: ${DOMAIN}
    links:
      - db
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  app:
    build:
      context: app
      target: "prod"
    volumes:
      - static:/app/dist/client/.next
    links:
      - admin

  ingress:
    build:
      context: docker/ingress
      target: "prod"
    links:
      - app
      - admin
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl:/var/lib/https-portal
      - static:/etc/nginx/html/_next:ro
    environment:
      STAGE: local
      DOMAINS: '${DOMAIN}'
      ACCESS_LOG: 'true'

volumes:
  static:
  ssl:
