version: "3.4"

services:
  admin:
    build:
      context: admin
      target: "dev"
    volumes:
      - ./admin:/app
    links:
      - db
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - data:/data/postgres
    ports:
      - '5432:5432'

  app:
    build:
      context: app
      target: "dev"
    links:
      - admin
    volumes:
      - ./app:/app:rw
    ports:
      - '3000:3000'
      - '9229:9229'

  web:
    build:
      context: docker/nginx
      target: "dev"
    links:
      - app
      - admin
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/502.html:/etc/nginx/html/502.html
      - ./app/src/client/.next:/etc/nginx/html/_next

  ingress:
    build:
      context: docker/ingress
    links:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl:/var/lib/https-portal
    environment:
      STAGE: local
      DOMAINS: '${DOMAIN} -> http://web'
      ACCESS_LOG: 'true'

volumes:
  ssl:
  data:
